### ISSUE TITLE
Stable version page needs updating re container deployment

### ISSUE THREAD

**Issue by simonflood** [uyuni-project/uyuni-project.github.io#105]
https://www.uyuni-project.org/pages/stable-version.html

With container deployment now preferred (and soon to be only) method of installing Uyuni the above page needs updating to reflect this. Currently it covers installing Uyuni (in legacy mode) on Leap 15.5 so anyone now coming to Uyuni might follow this only to then have to migrate/reinstall with container. I'd suggest now is the time to update these "quick start" instructions for container install.

**Comment by rjmateus** [comment]
thank you for point it. We are still working on improving documentation.
@jcayouette @deneb-alpha for awareness

**Comment by deneb-alpha** [comment]
thanks  @simonflood / @rjmateus .

We should provide additional fixes to  those pages with  Uyuni 2024.06 and Uyuni 2024.07

**Comment by raulillo82** [comment]
I'm looking into this and already have some changes for both stable/devel web pages. I will need reviews, but they will come out with 2024.10 release.
