### ISSUE TITLE
 Improve Uyuni website responsiveness across different devices

### ISSUE THREAD

**Issue by Rakielle** [uyuni-project/uyuni-project.github.io#91]
# Details

As part of [openSUSE/mentoring#205](https://github.com/openSUSE/mentoring/issues/205), this issue hopes to improve the responsiveness of Uyuni website.
The current Uyuni website is not responsive across different screen sizes, and this affects the experience of users accessing the site on mobile devices, tablets, and smaller desktop screens.
Also, this issue affects how screen readers interpret and read the website's content, as many elements overlap.
<br>
<img src="https://github.com/uyuni-project/uyuni-project.github.io/assets/48498778/0b805748-1d2d-4638-a547-fcd17bda0cec" alt="img1" height="350">
<img src="https://github.com/uyuni-project/uyuni-project.github.io/assets/48498778/e1c67d8c-4447-4ebd-bc11-12b802d9cd04" alt="img2" height="350">

To fix this, we could add CSS media queries to adjust the layout and styling based on viewport size.

**Comment by Sauradip07** [comment]
Please assign this issue to me
