### ISSUE TITLE
Fix Low Contrast Errors

### ISSUE THREAD

**Issue by Rakielle** [uyuni-project/uyuni-project.github.io#93]
# Details

As part of [openSUSE/mentoring#205](https://github.com/openSUSE/mentoring/issues/205), the goal of this issue is to improve the low contrast errors identified by WAVE.

**1. Very low contrast between texts and background colours:**
WAVE identified sections where the text and background colours have very low contrast.  This presents a challenge for users with visual impairments.
According to the WCAG, the minimum recommended contrast ratio for normal text should be 4.5:1. and the contrast ratios of the identified errors fall below this requirement.
</br>
<img src="https://github.com/uyuni-project/uyuni-project.github.io/assets/48498778/5d6694c2-8d88-4edb-9baf-f328106428b8" alt="img3" height="300">
<img src="https://github.com/uyuni-project/uyuni-project.github.io/assets/48498778/3c709535-4a36-473c-aefe-a0358328117e" alt="img4" width="300">
<img src="https://github.com/uyuni-project/uyuni-project.github.io/assets/48498778/a04c5a46-4aec-4928-b2c3-d0410e32eb4f" alt="img5" width="300"></br>

This can be fixed by increasing the contrast between the foreground and background colours, while still maintaining Uyuni theme colours. 
# Reference
[Contrast Minimum](https://webaim.org/standards/wcag/checklist#sc1.4.3)

**Comment by Sauradip07** [comment]
Please assign this issue to me
