### ISSUE TITLE
Go back Button 

### ISSUE THREAD

**Issue by aymansuhail** [uyuni-project/uyuni-project.github.io#96]
As part of [https://github.com/openSUSE/mentoring/issues/205](https://github.com/openSUSE/mentoring/issues/205) this issue hopes to improve the responsiveness of Uyuni website.
The current Uyuni website is not responsive across different screen sizes, and this affects the experience of users accessing the site on mobile devices, tablets, and smaller desktop screens.
Also, this issue affects how screen readers interpret and read the website's content, as many elements overlap.

![Go_back_button_Contactpage](https://github.com/uyuni-project/uyuni-project.github.io/assets/81426384/a3457152-aadc-4cc4-867e-795b1db88905)

![Go_back_button_NewzPagepng](https://github.com/uyuni-project/uyuni-project.github.io/assets/81426384/46b1c17a-57d5-49dd-ae30-36c9a56ea1e8)

To fix this, we could add CSS media queries to adjust the layout and styling based on viewport size.

**Comment by deneb-alpha** [comment]
fixed  by https://github.com/uyuni-project/uyuni-project.github.io/pull/136
